### ISSUE TITLE
merge node-spi and pi-spi?

### ISSUE THREAD

**Issue by RussTheAerialist** [natevw/pi-spi#17]
You seem to be doing much more SPI dev work with node than me (original author of node-spi).  Most everything I do no longer uses spi, and I don't feel like maintaining node-spi any longer.  Since you are already using NaN and support 4.x, should these two modules just merge (or rather, deprecate mine and just point people to yours?)

**Comment by natevw** [comment]
Hi, Russell and thanks for reaching out! I can't say I've had as much time to push forward on my own h/w projects as I'd like, but this library has been easy enough to keep up to date meanwhile.

Looks like the APIs are a bit different between this and your [node-spi](https://github.com/RussTheAerialist/node-spi#node-spi) but wouldn't be too hard for someone to wrap this in a compatibility shim if they wanted. IIRC the main reason I originally went ahead with this version was an original intent to keep it matched with [Tessel's SPI](https://github.com/tessel/t1-docs/blob/master/hardware-api.md#spi) interface — which didn't end up 100% happening after all — and was probably worried about being non-blocking just in case. [As an aside, I've found node.js to benefit the hardware *apps* nicely, but the async sure can make the drivers themselves complicated and cluttered!]

Anyway, no problem to have you link/refer people here if you'd like. Of course anyone currently using your module will have to decide for themselves whether to port over to this, or step up and get node-spi going again too. Best wishes from over the mountains, and happy hacking!

**Comment by natevw** [comment]
It looks like node-spi has been retired. I don't think there's much that we need to do here since I'm assuming anyone who needed to has manually ported the differences already.
