### ISSUE TITLE
Fail to install stub on windows 10 platform

### ISSUE THREAD

**Issue by johngrabner** [natevw/pi-spi#23]
I believe the intention of your module is to install a non functioning stub on windows 10 environment.
pi-spi does not build and therefore does not install.

Microsoft Windows [Version 10.0.10586](c) 2015 Microsoft Corporation. All rights reserved.

C:\Users\John>node -v
v4.4.5

C:\Users\John>npm install natevw/pi-spi
|

> pi-spi@1.0.1 install C:\Users\John\node_modules\pi-spi
> node-gyp rebuild

C:\Users\John\node_modules\pi-spi>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:401:14)
gyp ERR! stack     at C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:356:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\Program Files (x86)\nodejs\node.exe" "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\John\node_modules\pi-spi
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files (x86)\nodejs\node.exe" "C:\Program Files (x86)\nodejs\node_modules\npm\bin\npm-cli.js" "install" "natevw/pi-spi"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE

npm ERR! pi-spi@1.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pi-spi@1.0.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pi-spi package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pi-spi
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls pi-spi
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\John\npm-debug.log

C:\Users\John>

---

the npm-debug.log contains the following

[snipped] <ins>edit by @natevw — I [moved this to a gist](https://gist.github.com/natevw/2eb2b7a69362d0535b111ccf78fbe832)</ins>

**Comment by natevw** [comment]
Based on what I gather from this thread, the remaining issue here seems more related to a misconfigured environment, so I think this is not something I can fix. Please feel free to re-open if I'm wrong and there's still followup needed here.
