### ISSUE TITLE
Fix Build on Node 12

### ISSUE THREAD

**Issue by drothmaler** [natevw/pi-spi#28]
Currently pi-spi fails to build on Node.JS 12.x
Would be nice, if this could be fixed...

**Comment by natevw** [comment]
Looks like this is due to https://electronjs.org/blog/nodejs-native-addons-and-electron-5, hopefully an easy fix though I'm a bit curious as to backwards compatibility implications.

**Comment by natevw** [comment]
Ended up being quite a few other things that needed update, but it's now compiling for me under node v12.3.1. Published the fixes as `pi-spi@1.2.0`. Thanks for the report @drothmaler!
